### ISSUE TITLE
Automatically logging in without info

### ISSUE THREAD

**Issue by KracelKany** [aws-samples/serverless-games-on-aws#2]
Why is that it I can login without giving any username or password? The sign-up works, but I can login without authenticating. I can't seem to find how to correct this

**Comment by BatteryAcid** [comment]
Could it be because you have Unauthenticated identities enabled under the identity pool configuration?  I believe the instructions say to enable it for this sample, but you don't have to.
https://serverless-game-analytics.workshop.aws/en/cognito/cognito-identity-pools.html

**Comment by KracelKany** [comment]
I forgot to update this. The problem was in the Unity part. Especially the logging in code. It did not check for successful a login, whether authenticated or not. It threw an error(about the unsuccessful authentication) which I caught with android debugger and then the panel (which would load after logging in) loaded. 

So the culprit was in the logging in & loading code as it would try to authenticate after pressing the button and then loading the next panel regardless of whatever happened before.
